### ISSUE TITLE
VGA video output

### ISSUE THREAD

**Issue by old-delab** [sdima1357/spectrum128_esp32_usb_host_pal_tv#1]
Could you make an option with video output over VGA (bitluni's ESP32Lib). As, for example, in dcrespo3d/ZX-Spectrum-Wiimote. It would be a hit!

**Comment by sdima1357** [comment]
> VGA (bitluni's  ESP32Lib)
I know. i've seen it.
VGA implementation of spectrum not so complicate but:
1 Original spectrum works PAL . PAL has 50Hz refresh(25 interleave). So each 20 milliseconds we have interrupt of screen. which used by most games. Regular  VGA has 60 or 75 Hz refresh. So part of games seems different from original.
2 I don't need spectrum  with VGA output.

**Comment by old-delab** [comment]
вот так получается:
...\esp\esp-idf\spectrum128_esp32_usb_host_pal_tv>make flash monitor
"make" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

---------- вся найденная информация -----------------
"а компиляция описана в https://github.com/sdima1357/spectru...sb_host_pal_tv - прямо на странице . Читайте , компилируйте"

"//set right esp32 env for me it:
>export IDF_PATH=$HOME/esp/esp-idf
>source $HOME/esp/esp-idf/export.sh               <--- это не проходит
//connect the board, build & flash
>git clone  https://github.com/sdima1357/spectrum128_esp32_usb_host_pal_tv
>cd spectrum128_esp32_usb_host_pal_tv
>make flash monitor"                                         <--- и это не проходит

- из описания трудно понять, как именно скомпилировать build
- если запускать idf.py build tv_out.c, то создается bootloader.bin, далее ошибки типа ../main/usb_host.h:59:1: warning: 'packed' attribute ignored [-Wattributes] } sCfgDesc;, undefined reference to `usb_process', и в конце - collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by sdima1357** [comment]
I add src into CMakefile.txt so You can build it with 
idf.py

remove all code and repeat with new content: (Все удалить и повторить с новым кодом)

export IDF_PATH=$HOME/esp/esp-idf

source $HOME/esp/esp-idf/export.sh

//connect the board, build & flash

git clone https://github.com/sdima1357/spectrum128_esp32_usb_host_pal_tv

cd spectrum128_esp32_usb_host_pal_tv

idf.py flash monitor

**Comment by ZPilot** [comment]
Где взять прошивку и как прошить?

**Comment by sdima1357** [comment]
> 

У меня собирается без проблем согласно readme под Ubunu 18.04.  Пишите мне прямо на почту sdima1357@gmail.com подробнее. Сотрите директорию spectrum128_esp32_usb_host_pal_tv и попробуйте еще раз (может падать на файле build - я его удалил)

remove all code and repeat with new content: (Все удалить и повторить с новым кодом)

export IDF_PATH=$HOME/esp/esp-idf

source $HOME/esp/esp-idf/export.sh

//connect the board, build & flash

git clone https://github.com/sdima1357/spectrum128_esp32_usb_host_pal_tv

cd spectrum128_esp32_usb_host_pal_tv

idf.py flash monitor
